/**
 * Centralized API Integration Hook for MainContent
 * This hook provides all backend API connections for the admin dashboard
 */

import { useState, useEffect, useCallback } from 'react';
import { ApiService, AuthManager, BACKEND_CONFIG } from '../constants/api/2backend-api-superset';
import CentralizedApi from '@/services/centralizedApi';

// Types for better TypeScript support - Updated to match backend schema
interface User {
  id?: string;           // Legacy support
  userId?: string;       // Backend generated userId
  fullName: string;      // Backend uses fullName
  FullName?: string;     // Legacy support
  username?: string;     // Legacy support
  email: string;
  password?: string;
  phone: string;
  role?: 'user' | 'employee';
  permissions?: string[];
  avatar?: string;
  faceId?: string;
  verificationStatus?: 'pending' | 'verified' | 'rejected';
  aadhaarPhoto?: string;
  uploadedPhoto?: string;
  lastLogin?: Date;
  status?: 'active' | 'suspended';
  createdAt?: Date;
  updatedAt?: Date;
}

interface Event {
  // Note: eventId is generated by the backend for DynamoDB
  eventId?: string;  // Made optional since backend will generate this
  name: string;
  description: string;
  location: string;
  date: string;
  startTime: string;
  endTime: string;
  totalTickets: number;
  ticketsSold?: number;
  ticketPrice: number;
  status: string;
  // IMPORTANT: Backend expects organizerId with a 'z', but our frontend uses organiserId with an 's'
  organiserId: string; // Frontend naming
  organizerId?: string; // Backend naming (used when sending to API)
  coverImage?: string;
}

// The "notify …" switch from the event create/edit forms. The backend reads it
// off the event payload and never stores it on the event.
export interface EventNotify {
  send: boolean;
  title?: string;
  body?: string;
}

interface Registration {
  registrationId: string;
  eventId: string;
  userId: string;
  registrationDate: string;
  status: string;
  checkInTime?: string;
  waitingStatus: string;
  faceVerificationStatus: string;
  ticketAvailabilityStatus: string;
  verificationAttempts: number;
  ticketIssued: boolean;
  adminBooked: boolean;
  adminOverrideReason?: string;
}

interface Organizer {
  _id?: string; // what the backend identifies an organiser by; it never sends organiserId
  organiserId: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  website?: string;
  description: string;
  contactPerson: string;
  status: string;
  totalRevenue: number;
  totalEvents: number;
  activeEvents: number;
}

interface DashboardStats {
  totalUsers: number;
  totalEvents: number;
  totalRegistrations: number;
  pendingVerifications: number;
  activeEvents: number;
  completedEvents: number;
  totalRevenue: number;
}

export const useApiIntegration = () => {
  // State management
  const [users, setUsers] = useState<User[]>([]);
  const [events, setEvents] = useState<Event[]>([]);
  const [registrations, setRegistrations] = useState<Registration[]>([]);
  const [organizers, setOrganizers] = useState<Organizer[]>([]);
  const [feedback, setFeedback] = useState<any[]>([]);
  const [dashboardStats, setDashboardStats] = useState<DashboardStats>({
    totalUsers: 0,
    totalEvents: 0,
    totalRegistrations: 0,
    pendingVerifications: 0,
    activeEvents: 0,
    completedEvents: 0,
    totalRevenue: 0
  });
  const [loading, setLoading] = useState({
    users: false,
    events: false,
    registrations: false,
    organizers: false,
    feedback: false,
    stats: false
  });
  const [errors, setErrors] = useState({
    users: null,
    events: null,
    registrations: null,
    organizers: null,
    feedback: null,
    stats: null
  });
  
  // Track if initial data has been loaded to prevent duplicate calls
  const [initialDataLoaded, setInitialDataLoaded] = useState(false);

  // Authentication helpers
  const isAuthenticated = useCallback(() => {
    return AuthManager.isAuthenticated();
  }, []);

  const getCurrentUser = useCallback(() => {
    return AuthManager.getUser();
  }, []);

  const login = useCallback(async (credentials: { email: string; password: string }) => {
    try {
      const response = await ApiService.post('/api/auth/login', credentials);
      return response;
    } catch (error) {
      throw new Error(`Login failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  const logout = useCallback(async () => {
    try {
      await ApiService.post('/api/auth/logout', {});
    } catch (error) {
      console.warn('Logout error:', error);
    }
  }, []);

  // Users Management
  const fetchUsers = useCallback(async () => {
    if (loading.users) return; // Prevent duplicate calls
    setLoading(prev => ({ ...prev, users: true }));
    console.log('🔄 Fetching users...');
    try {
      const responseData = await CentralizedApi.users.getAll();
      console.log('📥 Users API response:', responseData);

      // Normalize common response shapes to an array of users
      let usersArray: any[] = [];
      if (Array.isArray(responseData)) {
        usersArray = responseData;
      } else if ((responseData as any).users && Array.isArray((responseData as any).users)) {
        usersArray = (responseData as any).users;
      } else if ((responseData as any).data && Array.isArray((responseData as any).data.users)) {
        usersArray = (responseData as any).data.users;
      } else if ((responseData as any).data && Array.isArray((responseData as any).data)) {
        usersArray = (responseData as any).data;
      } else {
        usersArray = [];
      }

      console.log('✅ Setting users array:', usersArray.length, 'users');

      setUsers(usersArray);
      setErrors(prev => ({ ...prev, users: null }));
    } catch (error) {
      console.error('❌ Failed to fetch users:', error);
      setErrors(prev => ({ ...prev, users: error instanceof Error ? error.message : 'Failed to fetch users' }));
      setUsers([]); // Ensure users is always an array even on error
    } finally {
      setLoading(prev => ({ ...prev, users: false }));
    }
  }, [loading.users]);

  // Force fetch users (bypasses loading check)
  const forceRefreshUsers = useCallback(async () => {
    setLoading(prev => ({ ...prev, users: true }));
    console.log('🔄 Force refreshing users...');
    try {
      const response = await ApiService.get<{data?: any; users?: any[]}>('/api/users');
      console.log('📥 Users API response (force):', response);

      // ApiService.get returns parsed JSON, not wrapped in .data
      let usersArray: any[] = [];
      if (Array.isArray(response)) {
        usersArray = response;
      } else if (response?.users && Array.isArray(response.users)) {
        usersArray = response.users;
      } else if (response?.data && 'users' in response.data && Array.isArray(response.data.users)) {
        usersArray = response.data.users;
      } else if (response?.data && Array.isArray(response.data)) {
        usersArray = response.data;
      } else {
        usersArray = [];
      }

      console.log('✅ Setting users array (force):', usersArray.length, 'users');

      setUsers(usersArray);
      setErrors(prev => ({ ...prev, users: null }));
    } catch (error) {
      console.error('❌ Failed to force fetch users:', error);
      setErrors(prev => ({ ...prev, users: error instanceof Error ? error.message : 'Failed to fetch users' }));
      setUsers([]); // Ensure users is always an array even on error
    } finally {
      setLoading(prev => ({ ...prev, users: false }));
    }
  }, []);

  const createUser = useCallback(async (userData: Partial<User>, skipRefresh = false) => {
    try {
      const response = await ApiService.post('/api/user', userData);
      if (!skipRefresh) {
        await fetchUsers(); // Refresh the list
      }
      return response;
    } catch (error) {
      throw new Error(`Failed to create user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchUsers]);

  const updateUser = useCallback(async (userId: string, updateData: Partial<User>, skipRefresh = false) => {
    try {
      const response = await CentralizedApi.users.update(userId, updateData);
      
      // Update local state immediately for better UX
      if (response && !skipRefresh) {
        setUsers(prevUsers => 
          prevUsers.map(user => 
            ((user as any)._id || (user as any).id || (user as any).userId) === userId 
              ? { ...user, ...updateData }
              : user
          )
        );
        // Then fetch fresh data to ensure consistency
        setTimeout(() => fetchUsers(), 100);
      }
      
      return response;
    } catch (error) {
      console.error('User update failed:', error);
      throw new Error(`Failed to update user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchUsers]);

  const verifyUser = useCallback(async (userId: string, skipRefresh = false) => {
    try {
      // Update the user's verification status to 'verified'
      const response = await CentralizedApi.users.verify(userId, 'verified');
      
      // If verification is successful, optionally update local state immediately
      if (response && !skipRefresh) {
        setUsers(prevUsers => 
          prevUsers.map(user => 
            ((user as any)._id || (user as any).id || (user as any).userId) === userId 
              ? { ...user, verificationStatus: 'verified' }
              : user
          )
        );
        // Then fetch fresh data to ensure consistency
        setTimeout(() => fetchUsers(), 100);
      }
      
      return response;
    } catch (error) {
      console.error('User verification failed:', error);
      throw new Error(`Failed to verify user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchUsers]);

  const rejectUser = useCallback(async (userId: string, skipRefresh = false) => {
    try {
      // Update the user's verification status to 'rejected'
      const response = await CentralizedApi.users.update(userId, {
        verificationStatus: 'rejected'
      });
      
      // If rejection is successful, optionally update local state immediately
      if (response && !skipRefresh) {
        setUsers(prevUsers => 
          prevUsers.map(user => 
            ((user as any)._id || (user as any).id || (user as any).userId) === userId 
              ? { ...user, verificationStatus: 'rejected' }
              : user
          )
        );
        // Then fetch fresh data to ensure consistency
        setTimeout(() => fetchUsers(), 100);
      }
      
      return response;
    } catch (error) {
      console.error('User rejection failed:', error);
      throw new Error(`Failed to reject user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchUsers]);

  // Events Management
  const fetchEvents = useCallback(async () => {
    setLoading(prev => ({ ...prev, events: true }));
    try {
      const response = await ApiService.get<{data?: any; events?: any[]}>('/api/events');
      const eventData = response?.events || (response?.data && 'events' in response.data ? response.data.events : response?.data) || response || [];
      // Ensure we always set an array
      setEvents(Array.isArray(eventData) ? eventData : []);
      setErrors(prev => ({ ...prev, events: null }));
    } catch (error) {
      setErrors(prev => ({ ...prev, events: error instanceof Error ? error.message : 'Failed to fetch events' }));
      setEvents([]); // Ensure events is always an array even on error
    } finally {
      setLoading(prev => ({ ...prev, events: false }));
    }
  }, []);

  const createEvent = useCallback(async (eventData: Partial<Event> & { notify?: EventNotify }) => {
    try {
      // Get the token from localStorage
      const token = localStorage.getItem('authToken');
      
      // Log the form data we received
      console.log('🔍 Raw eventData received:', eventData);
      
      // Just pass the minimal required fields
      // IMPORTANT: Using 'organizerId' (with z) instead of 'organiserId' (with s)
      // to match the backend requirements
      const minimalEvent = {
        name: eventData.name,
        description: eventData.description || '',
        location: eventData.location,
        date: eventData.date,
        startTime: eventData.startTime,
        endTime: eventData.endTime,
        totalTickets: Number(eventData.totalTickets),
        ticketPrice: Number(eventData.ticketPrice),
        status: eventData.status || 'draft',
        organizerId: eventData.organiserId, // Convert 'organiserId' to 'organizerId' for the backend
        ...(eventData.notify && { notify: eventData.notify }),
      };
      
      console.log('📤 Sending minimal event data:', minimalEvent);
      
      // Make a direct fetch call with minimal data
      const responseData = await ApiService.post('/api/events', minimalEvent);
      console.log('✅ Event creation successful:', responseData);
      await fetchEvents(); // Refresh the list
      return responseData;
    } catch (error) {
      console.error('❌ Event creation error:', error);
      
      // More detailed error logging
      if (error instanceof Error) {
        console.error('Error message:', error.message);
        console.error('Error stack:', error.stack);
      } else {
        console.error('Unknown error type:', error);
      }
      
      throw new Error(`Failed to create event: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchEvents]);

  const updateEvent = useCallback(async (eventId: string, updateData: Partial<Event> & { notify?: EventNotify }) => {
    try {
      const response = await ApiService.patch(`/api/events/${eventId}`, updateData);
      await fetchEvents(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to update event: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchEvents]);

  const deleteEvent = useCallback(async (eventId: string) => {
    try {
      const response = await ApiService.deleteRequest(`/api/events/${eventId}`);
      await fetchEvents(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to delete event: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchEvents]);

  // Registrations Management
  const fetchRegistrations = useCallback(async () => {
    setLoading(prev => ({ ...prev, registrations: true }));
    try {
      const response = await ApiService.get<{data?: {registrations?: any[]} | any[]; registrations?: any[]}>('/api/registrations');
      const registrationData = response?.registrations || (response?.data && 'registrations' in response.data ? response.data.registrations : response?.data) || response || [];
      // Ensure we always set an array
      setRegistrations(Array.isArray(registrationData) ? registrationData : []);
      setErrors(prev => ({ ...prev, registrations: null }));
    } catch (error) {
      setErrors(prev => ({ ...prev, registrations: error instanceof Error ? error.message : 'Failed to fetch registrations' }));
      setRegistrations([]); // Ensure registrations is always an array even on error
    } finally {
      setLoading(prev => ({ ...prev, registrations: false }));
    }
  }, []);

  const createRegistration = useCallback(async (registrationData: Partial<Registration>) => {
    try {
      const response = await ApiService.post('/api/registrations', registrationData);
      await fetchRegistrations(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to create registration: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchRegistrations]);

  const checkInUser = useCallback(async (registrationId: string) => {
    try {
      const response = await ApiService.put(`/api/registrations/${registrationId}/checkin`, {});
      await fetchRegistrations(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to check in user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchRegistrations]);

  const startFaceVerification = useCallback(async (registrationId: string, faceVerificationId: string) => {
    try {
      const response = await ApiService.put(
        `/api/registrations/${registrationId}/face-verification/start`,
        { faceVerificationId }
      );
      await fetchRegistrations(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to start face verification: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchRegistrations]);

  const completeFaceVerification = useCallback(async (
    registrationId: string, 
    success: boolean, 
    ticketAvailable: boolean
  ) => {
    try {
      const response = await ApiService.put(
        `/api/registrations/${registrationId}/face-verification/complete`,
        { success, ticketAvailable }
      );
      await fetchRegistrations(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to complete face verification: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchRegistrations]);

  const issueTicket = useCallback(async (registrationId: string) => {
    try {
      const response = await ApiService.put(`/api/registrations/${registrationId}/issue-ticket`, {});
      await fetchRegistrations(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to issue ticket: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchRegistrations]);

  const adminOverride = useCallback(async (
    registrationId: string, 
    overrideReason: string, 
    issueTicket: boolean = false
  ) => {
    try {
      const response = await ApiService.put(
        `/api/registrations/${registrationId}/admin-override`,
        { overrideReason, issueTicket }
      );
      await fetchRegistrations(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to process admin override: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchRegistrations]);

  // Organizers Management
  const fetchOrganizers = useCallback(async () => {
    console.log('🚀 fetchOrganizers function called!');
    setLoading(prev => ({ ...prev, organizers: true }));
    console.log('🔄 Fetching organizers...');
    try {
      const response = await ApiService.get<{data?: {organizers?: any[]} | any[]; organizers?: any[]}>('/api/organizers');
      console.log('📥 Organizers API response:', response);
      
      // Handle the nested data structure from your API
      const organizerData = response?.organizers || (response?.data && 'organizers' in response.data ? response.data.organizers : response?.data) || response || [];
      console.log('👥 Processed organizer data:', organizerData);
      
      // Ensure we always set an array
      const organizersArray = Array.isArray(organizerData) ? organizerData : [];
      console.log('✅ Setting organizers array:', organizersArray.length, 'organizers');
      setOrganizers(organizersArray);
      setErrors(prev => ({ ...prev, organizers: null }));
    } catch (error) {
      console.error('❌ Failed to fetch organizers from authenticated endpoint:', error);
      
      // Try public endpoint as fallback for testing
      try {
        console.log('🔄 Trying public organizers endpoint as fallback...');
        const publicResponse = await ApiService.get<{data?: any[] | any}>('/api/public/organizers');
        console.log('📥 Public organizers API response:', publicResponse);
        const publicOrganizerData = publicResponse?.data || publicResponse || [];
        console.log('👥 Processed public organizer data:', publicOrganizerData);
        const publicOrganizersArray = Array.isArray(publicOrganizerData) ? publicOrganizerData : [];
        console.log('✅ Setting organizers array from public endpoint:', publicOrganizersArray.length, 'organizers');
        setOrganizers(publicOrganizersArray);
        setErrors(prev => ({ ...prev, organizers: null }));
      } catch (publicError) {
        console.error('❌ Failed to fetch organizers from public endpoint:', publicError);
        setErrors(prev => ({ ...prev, organizers: error instanceof Error ? error.message : 'Failed to fetch organizers' }));
        setOrganizers([]); // Ensure organizers is always an array even on error
      }
    } finally {
      setLoading(prev => ({ ...prev, organizers: false }));
    }
  }, []);

  const createOrganizer = useCallback(async (organizerData: Partial<Organizer>) => {
    try {
      const response = await ApiService.post('/api/organizers', organizerData);
      await fetchOrganizers(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to create organizer: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchOrganizers]);

  const updateOrganizer = useCallback(async (organizerId: string, updateData: Partial<Organizer>) => {
    try {
      const response = await ApiService.patch(`/api/organizers/${organizerId}`, updateData);
      await fetchOrganizers(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to update organizer: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchOrganizers]);

  const deleteOrganizer = useCallback(async (organizerId: string) => {
    try {
      const response = await ApiService.deleteRequest(`/api/organizers/${organizerId}`);
      await fetchOrganizers(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to delete organizer: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchOrganizers]);

  // Dashboard Statistics
  const fetchDashboardStats = useCallback(async () => {
    setLoading(prev => ({ ...prev, stats: true }));
    try {
      const [eventStats, registrationStats] = await Promise.all([
        ApiService.get<{data?: {totalEvents?: number, activeEvents?: number, completedEvents?: number, totalRevenue?: number}}>('/api/events/stats')
          .catch(() => ({ totalEvents: 0, activeEvents: 0, completedEvents: 0, totalRevenue: 0 })),
        ApiService.get<{data?: {statusStats?: any[], ticketStats?: {totalRegistrations?: number}}}>('/api/registrations/stats')
          .catch(() => ({ statusStats: [], ticketStats: { totalRegistrations: 0 } }))
      ]);

      // Ensure we have arrays for calculations
      const usersArray = Array.isArray(users) ? users : [];
      const registrationsArray = Array.isArray(registrations) ? registrations : [];

      // Type assertion for the responses
      const typedEventStats = eventStats as any;
      const typedRegistrationStats = registrationStats as any;

      const stats: DashboardStats = {
        totalUsers: usersArray.length,
        totalEvents: typedEventStats.data?.totalEvents || typedEventStats.totalEvents || 0,
        totalRegistrations: typedRegistrationStats.data?.ticketStats?.totalRegistrations || registrationsArray.length,
        pendingVerifications: registrationsArray.filter(r => r.faceVerificationStatus === 'pending').length,
        activeEvents: typedEventStats.data?.activeEvents || typedEventStats.activeEvents || 0,
        completedEvents: typedEventStats.data?.completedEvents || typedEventStats.completedEvents || 0,
        totalRevenue: typedEventStats.data?.totalRevenue || typedEventStats.totalRevenue || 0
      };

      setDashboardStats(stats);
      setErrors(prev => ({ ...prev, stats: null }));
    } catch (error) {
      setErrors(prev => ({ ...prev, stats: error instanceof Error ? error.message : 'Failed to fetch dashboard stats' }));
    } finally {
      setLoading(prev => ({ ...prev, stats: false }));
    }
  }, []); // Remove dependency on arrays to prevent infinite loops

  // File Upload (for face recognition)
  const uploadImage = useCallback(async (imageFile: File, fullName: string) => {
    try {
      const response = await ApiService.post('/api/auth/upload', {
        image: imageFile,
        fullname: fullName
      });
      return response;
    } catch (error) {
      throw new Error(`Failed to upload image: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  // Feedback Management
  const fetchFeedback = useCallback(async () => {
    setLoading(prev => ({ ...prev, feedback: true }));
    try {
      const response = await ApiService.get<{data?: {feedback?: any[]} | any[]; feedback?: any[]}>('/api/feedback');
      const feedbackData = response?.feedback || (response?.data && 'feedback' in response.data ? response.data.feedback : response?.data) || response || [];
      setFeedback(Array.isArray(feedbackData) ? feedbackData : []);
      setErrors(prev => ({ ...prev, feedback: null }));
    } catch (error) {
      setErrors(prev => ({ ...prev, feedback: error instanceof Error ? error.message : 'Failed to fetch feedback' }));
      setFeedback([]); // Ensure feedback is always an array even on error
    } finally {
      setLoading(prev => ({ ...prev, feedback: false }));
    }
  }, []);

  const createFeedback = useCallback(async (feedbackData: any) => {
    try {
            const response = await ApiService.post('/api/feedback', feedbackData);
      await fetchFeedback(); // Refresh the list
      return response;
    } catch (error) {
      throw new Error(`Failed to create feedback: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, [fetchFeedback]);

  // Admin Functions
  const createEmployee = useCallback(async (employeeData: any) => {
    try {
            const response = await ApiService.post('/api/admin/employees', employeeData);
      return response;
    } catch (error) {
      throw new Error(`Failed to create employee: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  const createAdminUser = useCallback(async (adminUserData: any) => {
    try {
            const response = await ApiService.post('/api/admin/admin-users', adminUserData);
      return response;
    } catch (error) {
      throw new Error(`Failed to create admin user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  const getAllAdminUsers = useCallback(async () => {
    try {
            const response = await ApiService.get('/api/admin/admin-users');
      return response;
    } catch (error) {
      throw new Error(`Failed to fetch admin users: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  const updateAdminUser = useCallback(async (adminUserId: string, updateData: any) => {
    try {
            const response = await ApiService.patch(`/api/admin/admin-users/${adminUserId}`, updateData);
      return response;
    } catch (error) {
      throw new Error(`Failed to update admin user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  const deleteAdminUser = useCallback(async (adminUserId: string) => {
    try {
            const response = await ApiService.deleteRequest(`/api/admin/admin-users/${adminUserId}`);
      return response;
    } catch (error) {
      throw new Error(`Failed to delete admin user: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  const getActivityLog = useCallback(async () => {
    try {
            const response = await ApiService.get('/api/admin/activity');
      return response;
    } catch (error) {
      throw new Error(`Failed to fetch activity log: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }, []);

  // Refresh all data
  const refreshAllData = useCallback(async () => {
    console.log('🔄 refreshAllData called');
    const fetchPromises = [
      fetchUsers(),
      fetchEvents(),
      fetchRegistrations(),
      fetchOrganizers(),
      fetchFeedback() // Add fetchFeedback to refresh all data
    ];
    
    console.log('📞 Starting parallel API calls...');
    await Promise.all(fetchPromises);
    console.log('✅ All API calls completed');
    
    // Fetch dashboard stats after a small delay to ensure data is loaded
    setTimeout(() => {
      console.log('📊 Fetching dashboard stats...');
      fetchDashboardStats();
    }, 200);
  }, [fetchUsers, fetchEvents, fetchRegistrations, fetchOrganizers, fetchFeedback]);

  // Initialize data on mount - run only once
  useEffect(() => {
    console.log('🚀 useApiIntegration useEffect triggered', {
      isAuthenticated: isAuthenticated(),
      loadingUsers: loading.users,
      loadingEvents: loading.events,
      loadingRegistrations: loading.registrations,
      loadingOrganizers: loading.organizers
    });
    
    if (isAuthenticated()) {
      console.log('✅ User is authenticated, refreshing all data...');
      refreshAllData();
    } else {
      console.log('❌ User is not authenticated');
    }
  }, [isAuthenticated]); // Removed refreshAllData from dependencies to prevent infinite loops

  return {
    // Data
    users,
    events,
    registrations,
    organizers,
    feedback, // Add feedback to the return object
    dashboardStats,
    loading,
    errors,

    // Authentication
    isAuthenticated,
    getCurrentUser,
    login,
    logout,

    // Users
    fetchUsers,
    forceRefreshUsers,
    createUser,
    updateUser,
    verifyUser,
    rejectUser,

    // Events
    fetchEvents,
    createEvent,
    updateEvent,
    deleteEvent,

    // Registrations
    fetchRegistrations,
    createRegistration,
    checkInUser,
    startFaceVerification,
    completeFaceVerification,
    issueTicket,
    adminOverride,

    // Organizers
    fetchOrganizers,
    createOrganizer,
    updateOrganizer,
    deleteOrganizer,

    // Dashboard
    fetchDashboardStats,

    // Utilities
    uploadImage,
    createFeedback,
    fetchFeedback, // Add fetchFeedback to the return object
    
    // Admin Management
    createEmployee,
    createAdminUser,
    getAllAdminUsers,
    updateAdminUser,
    deleteAdminUser,
    getActivityLog,
    
    refreshAllData
  };
};
